name: banan_design_system
description: Banan design system — tokens, theme, responsive primitives, base widgets.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  banan_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
